### ISSUE TITLE
Interacting with the features in Rust, and the parsing of dat files in FTL 1.6.1 and above

### ISSUE THREAD

**Issue by C20H12** [itb-community/ftldat-rs#1]
Hi, an FTL modder and beginner at Rust here, just have a couple of questions:

- Is it possible to access the functions and use them directly in a Rust program instead of Lua? Specifically, the `pack:content_text_by_path` function since I am planning to read some weapons data from the blueprints.
- If so, how and which ones?
- Will this repo be made into a crate so that it is easier to access with Rust?

**Comment by kartoFlane** [comment]
It should be possible to use this library in your project, though since it's not available as a crate, you'd probably have to copy its source code, and alter it to use it as a rust module (preferably cutting out the parts that integrate with lua).

Most of the functions you need to interact with the .dat file should be publicly accessible and annotated with docs. Generally, the pattern would be:
```rust
// Read the .dat file - this can fail (file doesn't exist, corrupt file, etc.),
// so you'll need to add some error handling
let package = FtlDatPackage::from_file("path/to/resources.dat").unwrap();
// Functions that read content from the .dat file return Option, so you'll
// need to handle that as well
let content = package.string_content_by_path("inner_path/within/archive").unwrap();
```

I didn't have plans to publish this repo as a crate, but I'll have some free time in the latter half of December, so I can try looking into it.

**Comment by C20H12** [comment]
Thanks for your response. 
But I tried it in my project and it didn't seem to work. Here's the code
```rs
use ftldat::prelude::*;

fn main() {
  let package = FtlDatPackage::from_file("some_path\ftl.dat").unwrap();
  let content: String = package.content_by_path("data/blueprints.xml").unwrap();
  print!("{}", content);
}
```
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ReadEntryError(ReadByteError(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }))'
```
I checked the integrity of the dat file and it seems to be ok., and the paths are correct  Any ideas?

**Comment by kartoFlane** [comment]
I tested this on my end, seems that FTL's .dat file somehow does things differently, and the library fails to read it. I'll have to take a closer look, since the formats are *supposed* to be the same.

Also, I had two commits on my local repo that I forgot to push, which is where the differences between `string_content_by_path` and `content_by_path` came from.

**Comment by kartoFlane** [comment]
Alright, I dug out why this lib doesn't work - FTL originally used the .dat format this lib implements, and that's why we could use old FTL modding tools for ITB modding (such as [this one](https://subsetgames.com/forum/viewtopic.php?f=12&t=2788), which is pinned in ITB's Discord). However, in version 1.6.1, FTL switched over to PKG format - this is [documented in SMM](https://github.com/Vhati/Slipstream-Mod-Manager/blob/master/src/main/java/net/vhati/ftldat/PkgPack.java#L33-L50).

The format is not too different (I think it pretty much only adds a `PKG\n` header and uses big endian instead of little endian?), but  enough to make it incompatible with existing implementation - we'd need a separate reader and writer structs for handling it. I think the existing `Package` struct should be sufficient to represent it in-memory, unless there are more differences I didn't pick up after briefly checking SMM's code.

**Comment by C20H12** [comment]
Yeah I see, there are a few different things with the current version's dat files.
I can wait until that's implemented. I'll stick to slipstream for now.

**Comment by kartoFlane** [comment]
I took me a bit of time to finish up all the things I wanted to before publishing this project as a crate, but it's finally available: https://crates.io/crates/ftldat

The docs are not perfect, but should be sufficient to use the library effectively.
